config/routes.rb
Rails.application.routes.draw do
  root 'reports#index'

  resources :reports, except: %w(new edit) do
    resources :tasks, controller: 'reports/tasks', only: %w(create update destroy)
  end

  resources :comments, only: %w(create update destroy)
  resource :profile, only: %w(show update)
end

app/views/layouts/_flash.html.erb
<% unless flash.empty? %>
  <div class="flash">
    <div class="flash-inner">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reports</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header"> <button type="button" class="collapsed navbar-toggle" data-toggle="collapse" data-aria-expanded="false"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button> <a href="#" class="navbar-brand">ReportsApp</a> </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <%= active_link_to 'Reports', reports_path, active: :exclusive, wrap_tag: :li %>
          </ul>

          <% if signed_in? %>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to current_user, profile_path, title: 'User Profile' %></li>
              <li><%= link_to 'Sign out', sign_out_path, method: :delete %></li>
            </ul>
          <% end %>
        </div>
      </div>
    </nav>

    <main class="main-container">
      <%= render partial: 'layouts/flash' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/restricted.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reports</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <main class="main-container">
      <%= render partial: 'layouts/flash' %>

      <%= yield %>
    </div>
  </body>
</html>